[versions]
accompanist_version = "0.26.1-alpha"
compiler_version = "1.3.0"
compose_version = "1.3.0-beta01"
material_version = "1.0.0-beta01"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "compose_version" }

accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist_version" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist_version" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist_version" }

ui = { module = "androidx.compose.ui:ui", version.ref = "compose_version" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_version" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose_version" }

material = { module = "androidx.compose.material3:material3", version.ref = "material_version" }

[bundles]
accompanist = ["accompanist-swiperefresh", "accompanist-flowlayout", "accompanist-systemuicontroller"]
activity = ["activity-compose"]
ui = ["ui", "ui-tooling", "ui-tooling-preview"]
material = ["material"]